### ISSUE TITLE
How to use pretrained Supernetwork weights from HW-GPT-Bench?

### ISSUE THREAD

**Issue by waterpeople** [automl/MODNAS#2]
Can you tell me how to use pretrained Supernetwork weights from HW-GPT-Bench? where is code?Thank you！

**Comment by rheasukthanker** [comment]
Thank you for raising the issue. We have now updated the code and instructions to perform search on the HW-GPT-Space. You can download the pretrained checkpoints from HW-GPT-Bench from [HW-GPT-Bench](https://github.com/automl/HW-GPT-Bench). Please fill free to re-open the issue if you have any further questions!
