### ISSUE TITLE
I'm encountering a problem when running train_llm_configurable.py.

### ISSUE THREAD

**Issue by waterpeople** [automl/MODNAS#5]
![1](https://github.com/user-attachments/assets/4aa47c66-69f7-4bed-aef6-800640e86600)

i can‘t find arch_energy_gpu_dataset.pkl and device_embeddings.pkl

**Comment by rheasukthanker** [comment]
Thanks for raising that issue! We have now uploaded these files [here](https://drive.google.com/drive/folders/15LaGiB038jFs648haYTrlRSG0owAlO7D?usp=sharing). Feel free re-open the issue if you are still missing some files!
